services:
    App\Application\Command\CommandBus:
        arguments:
            - '@service_container'

    App\Application\Command\Movie\MovieCreateCommandHandler:
        public: true
        arguments:
            - '@App\Infrastructure\Repository\MovieRepository'

    App\Application\Command\Movie\MovieDeleteCommandHandler:
        public: true
        arguments:
            - '@App\Infrastructure\Repository\MovieRepository'
