services:
    App\Infrastructure\Bus\Command\CommandBusAsync:
        arguments:
            - '@service_container'

    App\Application\Command\Movie\MovieCreateCommandHandler:
        public: true
        arguments:
            - '@App\Infrastructure\Repository\MovieRepositoryPomm'

    App\Application\Command\Movie\MovieDeleteCommandHandler:
        public: true
        arguments:
            - '@App\Infrastructure\Repository\MovieRepositoryPomm'
