services:
    App\Infrastructure\Shared\Bus\Query\QueryBusSymfonySync:
        arguments:
            - '@service_container'

    App\Application\Query\Movie\MovieFindQueryHandler:
        public: true
        arguments:
            - '@App\Infrastructure\Repository\MovieRepositoryPomm'
