services:
    App\Infrastructure\Repository\MovieRepositoryPomm:
        arguments:
            - '@App\Infrastructure\Model\Db\PublicSchema\MovieModel'
            - '@App\Infrastructure\DTO\MovieDTO'

    App\Infrastructure\Repository\UserRepositoryPomm:
        arguments:
            - '@App\Infrastructure\Model\Db\PublicSchema\UserModel'