nelmio_api_doc:
    documentation:
        models: { use_jms: true }
        info:
            title: Empleo
            description: This is an app to manage time of collaborators
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
