security:
    encoders:
        App\Infrastructure\Model\Db\PublicSchema\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            id: App\Infrastructure\Service\Provider\UserProvider

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        main:
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
