<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Infrastructure\Model\Db\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Movie.
 *
 * Structure class for relation public.movie.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 *
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 * @see RowStructure
 */
class Movie extends RowStructure
{
    /**
     * __construct.
     *
     * Structure definition.
     */
    public function __construct()
    {
        $this
            ->setRelation('public.movie')
            ->setPrimaryKey(['id'])
            ->addField('id', 'varchar')
            ->addField('exploitation_visa', 'varchar')
            ->addField('title', 'varchar')
            ->addField('year', 'int4')
            ;
    }
}
