parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Application\Controller\:
        resource: '../src/Application/Controller'
        tags: ['controller.service_arguments']

    ################### LISTENER ###################
    App\Application\EventListener\ExceptionListener:
        arguments:
            - '@jms_serializer'
            - '@translator.default'
            - '@App\Infrastructure\Service\Serializer\FormErrorsSerializer'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    ################### MODEL ###################
    App\Infrastructure\Model\Db\PublicSchema\UserModel:
        tags: [pomm.model]

    ################### REPOSITORY ###################
    App\Infrastructure\Repository\UserRepository:
        arguments:
            - '@App\Infrastructure\Model\Db\PublicSchema\UserModel'

    ################### PROVIDER ###################
    App\Infrastructure\Service\Provider\UserProvider:
        arguments:
            - '@App\Infrastructure\Repository\UserRepository'
            -
    ################### COMMAND ###################
    App\Infrastructure\Command\Command\CommandBus:
        arguments:
            - '@service_container'

    ################### SERIALIZER ###################
    App\Infrastructure\Service\Serializer\FormErrorsSerializer:
