imports:
    - { resource: "services/services_command.yaml" }
    - { resource: "services/services_query.yaml" }
    - { resource: "services/services_dto.yaml" }
    - { resource: "services/services_model.yaml" }
    - { resource: "services/services_repository.yaml" }
    - { resource: "services/services_repository_in_memory.yaml" }

parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: false

    App\UI\Http\Controller\:
        resource: '../src/UI/Http/Controller'
        tags: ['controller.service_arguments']

    ################### LISTENER ###################
    App\UI\Http\EventListener\ExceptionListener:
        arguments:
            - '@jms_serializer'
            - '@translator.default'
            - '@App\Infrastructure\Shared\Serializer\FormErrorsSerializer'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    ################### PROVIDER ###################
    App\Infrastructure\Provider\UserProvider:
        arguments:
            - '@App\Infrastructure\Repository\UserRepositoryPomm'

    ################### SERIALIZER ###################
    App\Infrastructure\Shared\Serializer\FormErrorsSerializer:

    ################### FORMATTER ###################
    App\UI\Http\Response\JsonApiFormatter:
